[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.build]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmds = [". .venv/bin/activate", "uvicorn main:app --host 0.0.0.0 --port $PORT"]
