[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
cmds = [
    "python3.11 -m venv .venv",
    ". .venv/bin/activate && pip install -U pip && pip install -r requirements.txt"
]

[start]
cmd = ". .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
